site_name: 'Magknight Documentation'
site_url: 'https://docs.magknight.org/'
repo_name: 'GitHub'
repo_url: 'https://github.com/magknight/aviatorsDocs'
site_description: "Documentation for the Magknight 787: Aviator's Edition for X-Plane 11, now stored in the cloud"
site_author: 'magknight'
copyright: 'magknight'

theme:
  name: 'material'
  language: 'en'
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  custom_dir: 'theme'
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.footnotes
  - markdown.extensions.toc:
      permalink: true
      separator: "_"
  - pymdownx.details
  - markdown.extensions.meta
nav:
  - Home: "index.md"
  - Frequently Asked Questions: "faq.md"
  - Troubleshooting: "troubleshooting.md"
  #- Tutorials:
  #  - Getting Started: "flightTutorial.md"
  - Reference:
    - Aircraft Settings: "aircraftSettings.md"
  - About: "about.md"
  
extra:
  social:
    - type: globe
      link: http://magknight.org
    - type: twitter
      link: https://twitter.com/magknightav
    - type: facebook
      link: https://www.facebook.com/magknightAv

# extra_javascript:
#     - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML
